name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm run test
      
  build:
    needs: test
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Determine Docker Tag
      id: docker_tag
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "TAG=pr-$(date +%Y%m%d)" >> $GITHUB_ENV
        else
          echo "TAG=latest" >> $GITHUB_ENV
        fi

    - name: Build the Backend Docker image
      run: docker build . --file Dockerfile --tag agalias-project-backend:$TAG
